
import type { Metadata } from 'next'
import { Inter, Rubik, Space_Grotesk, Space_Mono } from 'next/font/google'
import '../styles/globals.scss';
import Header from "@/components/Header";
import Footer from "@/components/Footer";

const space_grotesk = Space_Grotesk({
  subsets: ['latin'],
  display: 'swap',
  weight: ['400', '500', '600', '700'],
  variable: '--font-space_grotesk',
})
const space_mono = Space_Mono({
  subsets: ['latin'],
  display: 'swap',
  weight: ['400','700'],
  variable: '--font-space_mono',
})
const rubik = Rubik({
  subsets: ['latin'],
  display: 'swap',
  weight: ['400', '500', '600', '700'],
  variable: '--font-rubik',
})


export const metadata: Metadata = {
  title: 'Notion Blog',
  description: 'Generated by Javier',

}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  return (
    <html lang="en">
      <body className={`${space_grotesk.variable} ${space_mono.variable} ${rubik.variable}`}>
        <div className="flex w-full flex-col min-h-screen selection:bg-[#2cb67d] selection:text-[#fff]">
          <Header />
          {children}
          <Footer />
        </div>
      </body>
    </html>
  )
}
